services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-notifier-bot
    env_file:
      - .env
    volumes:
      - ./locales:/app/locales:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"